apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sit
namePrefix: chatbot-
commonLabels:
  app: chatbot

resources:
- service.yml
- deployment.yml

images:
- name: appImage
  newName: my.image.registry/nginx
  newTag: 1.4.0

patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: app
  path: patch.yml
