apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sit
namePrefix: chatbot-
commonLabels:
  app: chatbot

resources:
- service.yml
- deployment.yml

images:
- name: appImage
  newName: txconsole/chatbot
  newTag: "11"

patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: app
  path: deploy_patch.yml
- target:
    group:
    version: v1
    kind: Service
    name: app
  path: service_patch.yml
