apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: changeNameSpace
namePrefix: changeAppName-
commonLabels:
  app: changeAppName
resources:
- service.yml
- ingress.yml
- deployment.yml

images:
- name: appImage
  newName: changeImageRegURL/changeImageRepo/changeAppImage
  newTag: "changeImageTag"

patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: app
  path: deploy_patch.yml
- target:
    group:
    version: v1
    kind: Service
    name: app
  path: service_patch.yml
- target:
    group: networking.k8s.io
    version: v1beta1
    kind: Ingress
    name: app
  path: ingress_patch.yml
